# import = [
    # "themes/themes/snazzy.toml"
    # "themes/themes/wombat.toml"
    # "themes/themes/xterm.toml"
    # "themes/themes/iterm.toml"
    # "themes/themes/monokai_charcoal.toml"
    # "themes/themes/hyper.toml"
    # "themes/themes/midnight-haze.toml"
    # "themes/themes/ayu_dark.toml"
    # "themes/themes/catppuccin_mocha.toml"
    # "themes/themes/challenger_deep.toml"
    # "themes/themes/dracula.toml"
    # "themes/themes/github_dark_default.toml"
    # "themes/themes/github_dark_high_contrast.toml"
    # "themes/themes/hardhacker.toml"
    # "themes/themes/tokyo-night.toml"
    # "my_themes/gruber.toml"
    # "my_themes/lackluster.toml"
# ]

# LACKLUSTER COLORS
[colors.primary]
background = '#101010'

[colors.normal]
# black is gray0
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
# cyan is set to lack
cyan = '#708090' 
# white is set to luster
white = '#DEEEED'

[shell]
program = "fish"

[window]
# opacity = 0.95
# padding = { x = 0, y = 0 }
# decorations = "none" 
# dynamic_title = true
# dynamic_padding = true

[font]
# normal = { family = "Terminus" }
# normal = { family = "Iosevka" }
# normal = { family = "monospace"}
# normal = { family = "iMWritingMono Nerd Font" }
# normal = { family = "CaskaydiaCove Nerd Font Propo" }
# normal = { family = "CommitMono Nerd Font", style = "Regular" }
# normal = { family = "UbuntuSansMono Nerd Font" }
normal = { family = "MesloLGS Nerd Font" }
size = 11

[bell]
animation = "EaseOutCubic"
duration = 250
color = "#d18191"

[terminal]
osc52 = "CopyPaste"

[cursor]
style = { shape = "Block" , blinking = "On" }
vi_mode_style = { shape = "Block" , blinking = "On" } 
unfocused_hollow = true
thickness = 0.2

[scrolling]
history = 10000
multiplier = 8

[keyboard]
bindings = [
   { key = "Return", mods = "Shift|Alt", action = "SpawnNewInstance" }
]

[[hints.enabled]]
regex = "[^ ]+\\.*:\\d+:\\d+"
command = { program = "alacritty", args = [ "-e", "hx" ] }
mouse = { enabled = true }
