[general]
import = [
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Gruvbox-Light.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Gruvbox-Light.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Google.light.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Google.dark.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Zenburn.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Monokai.dark.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/3024.dark.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/One-Dark.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/vscode.dark.toml"
    # "./themes/themes/zenburn.toml"
    # "./themes/themes/github_dark.toml"
    # "./themes/themes/gruvbox_material.toml"
    # "./themes/themes/hyper.toml"
    # "./themes/themes/oxocarbon.toml"
    # "./my_themes/gruber.toml"
    # "./themes/themes/bluish.toml",
    "./themes/themes/gruvbox_material_hard_light.toml",
    # "./themes/themes/gruvbox_light.toml",
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Hyper.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Ayu-Mirage.toml"
    # "./themes/themes/hyper.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Base16-Default-Dark.toml"
    # "/usr/local/lib/node_modules/alacritty-themes/themes/Tokyonight_Night.toml"
]

[terminal]
osc52 = "CopyPaste"

[window]
# opacity = 0.9
decorations = "full"
dynamic_title = true
dynamic_padding = true
padding.x = 0
padding.y = 0

[font]
size = 10.5

	[font.normal]
    	# family = "JetBrainsMono Nerd Font"
        # family = "D2CodingLigature Nerd Font"
        # family = "VictorMono Nerd Font"
        # family = "IntoneMono Nerd Font"
    	# family = "M+1Code Nerd Font"
    	# family = "LiterationMono Nerd Font"
	    # family = "FiraCode Nerd Font"
    	# family = "Latin Modern Mono"
    	# family = "Lilex Nerd Font"
    	# family = "SauceCodePro Nerd Font"
    	# family = "Inconsolata Nerd Font"
    	# family = "NotoSansM Nerd Font"
    	# family = "CaskaydiaCove Nerd Font"
    	# family = "MonaspiceKr Nerd Font Mono"
    	# family = "SauceCodePro Nerd Font"
    	# family = "CodeNewRoman Nerd Font"
	    # family = "Iosevka Nerd Font Mono"
    	# family = "GohuFont 14 Nerd Font"
	    family = "Iosevka Nerd Font"
        # family = "BlexMono Nerd Font"
        # family = "ProggyClean CE Nerd Font"
        # family = "BigBlueTermPlus Nerd Font"
        # family = "Hurmit Nerd Font"
        # family = "DejaVuSansM Nerd Font"
        # family = "ComicShannsMono Nerd Font"
        # family = "Hack Nerd Font"
        # family = "ZedMono NFM"
        # family = "ComicShannsMono Nerd Font"
        # family = "Aporetic Sans Mono"
        # family = "MesloLGM Nerd Font"
        # family = "NewComputerModernMono10"

[bell]
animation = "EaseOutCubic"
duration = 100
color = "#d18191"

[cursor]
unfocused_hollow = true
thickness = 0.2

	[cursor.style]
	shape = "Block"
	blinking = "On"
	
	[cursor.vi_mode_style]
	shape = "Block"
	blinking = "On"

[scrolling]
history = 10_000
multiplier = 10

[[keyboard.bindings]]
key = "Return"
mods = "Shift|Alt"
action = "SpawnNewInstance"

[mouse]
hide_when_typing = true

[env]
term = "xterm-256color"

