[general]
import = [
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/Google.light.toml"
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/Google.dark.toml"
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/Zenburn.toml"
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/Monokai.dark.toml"
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/3024.dark.toml"
    	"/usr/local/lib/node_modules/alacritty-themes/themes/One-Dark.toml"
    	# "/usr/local/lib/node_modules/alacritty-themes/themes/vscode.dark.toml"
]

[terminal]
osc52 = "CopyPaste"

[window]
opacity = 0.9
decorations = "full"
dynamic_title = true
dynamic_padding = true
padding.x = 10
padding.y = 20

[font]
size = 12

	[font.normal]
    	# family = "JetBrains Mono Nerd Font"
    	# family = "M+1Code Nerd Font"
    	# family = "GohuFont 11 Nerd Font"
    	# family = "LiterationMono Nerd Font"
    	# family = "FiraCode Nerd Font"
    	# family = "Latin Modern Mono"
    	# family = "Lilex Nerd Font"
    	# family = "SauceCodePro Nerd Font"
    	# family = "Inconsolata Nerd Font"
    	# family = "NotoSansM Nerd Font"
    	# family = "CaskaydiaMono NFM Light"
    	# family = "MonaspiceKr Nerd Font Mono"
    	# family = "SauceCodePro Nerd Font"
    	# family = "CodeNewRoman Nerd Font"
	    # family = "Iosevka Nerd Font"
        # family = "ProggyClean CE Nerd Font"
        # family = "BigBlueTermPlus Nerd Font"
        # family = "Hurmit Nerd Font"
        # family = "DejaVuSansM Nerd Font"
        # family = "ComicShannsMono Nerd Font"
        family = "Hack Nerd Font"



[bell]
animation = "EaseOutCubic"
duration = 250
color = "#d18191"

[cursor]
unfocused_hollow = true
thickness = 0.2

	[cursor.style]
	shape = "Block"
	blinking = "On"
	
	[cursor.vi_mode_style]
	shape = "Block"
	blinking = "On"

[scrolling]
history = 10_000
multiplier = 10

[[keyboard.bindings]]
key = "Return"
mods = "Shift|Alt"
action = "SpawnNewInstance"

[mouse]
hide_when_typing = true

[env]
term = "xterm-256color"

