# Colors (Gruber)

# Default colors
[colors.primary]

    background = '#181818'
    foreground = '#f5f5f5'

[colors.cursor]

    cursor = '#f5f5f5'
    text = '#000000'

# Normal colors
[colors.normal]

    black   = '#000000'
    red     = "#f43841"
    green   = '#73c936'
    yellow  = '#ffdd33'
    # blue    = '#5292c8' # old
    blue    = '#6094bf' # new
    magenta = '#9e95c7'
    cyan    = '#9e95c7'
    white   = '#f5f5f5'

# Bright colors
[colors.bright]

    black   = '#52494e'
    red     = '#ff4f58'
    green   = '#33ff00'
    yellow  = '#feff00'
    blue    = '#96a6c8'
    magenta = '#9e95c7'
    cyan    = '#9e95c7'
    white   = '#FFFFFF'

# (gruber-darker-fg        "#e4e4ef")
# (gruber-darker-fg+1      "#f4f4ff")
# (gruber-darker-fg+2      "#f5f5f5")
# (gruber-darker-white     "#ffffff")
# (gruber-darker-black     "#000000")
# (gruber-darker-bg-1      "#101010")
# (gruber-darker-bg        "#181818")
# (gruber-darker-bg+1      "#282828")
# (gruber-darker-bg+2      "#453d41")
# (gruber-darker-bg+3      "#484848")
# (gruber-darker-bg+4      "#52494e")
# (gruber-darker-red-1     "#c73c3f")
# (gruber-darker-red       "#f43841")
# (gruber-darker-red+1     "#ff4f58")
# (gruber-darker-green     "#73c936")
# (gruber-darker-yellow    "#ffdd33")
# (gruber-darker-brown     "#cc8c3c")
# (gruber-darker-quartz    "#95a99f")
# (gruber-darker-niagara-2 "#303540")
# (gruber-darker-niagara-1 "#565f73")
# (gruber-darker-niagara   "#96a6c8")
# (gruber-darker-wisteria  "#9e95c7")


