return {
	{ "luisiacc/gruvbox-baby" },
    { "gruvbox-community/gruvbox" },
	{ "sainnhe/gruvbox-material" },
	-- { "ellisonleao/gruvbox.nvim" },
	{ "sainnhe/everforest" },
	{ "EdenEast/nightfox.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "AlexvZyl/nordic.nvim" },
	{ "craftzdog/solarized-osaka.nvim" },
	{ "cocopon/iceberg.vim" },
	{ "ayu-theme/ayu-vim" },
	{ "challenger-deep-theme/vim" },
	{ "nanotech/jellybeans.vim" },
	{ "rafi/awesome-vim-colorschemes" },
	{ "catppuccin/nvim" },
	{ "blazkowolf/gruber-darker.nvim" },
}
