use_nerdfont = true
flip_status_indicators = true
library_tabs = ["tracks", "playlists", "browse"]

[theme]
title = "yellow"
highlight_bg = "yellow"
highlight = "black"
playing = "yellow"
playing_selected = "black"

[keybindings]
"Ctrl+d" = "move down 10"
"Ctrl+u" = "move up 10"
"Shift+g" = "move bottom"
"g" = "move top"
"q" = "noop"
"Ctrl+q" = "focus queue"
"Ctrl+f" = "focus search"
"Ctrl+l" = "focus library"
"Ctrl+r" = "focus cover"
